name: drawable
description: Flutter plugin to load Android drawables. This helps to share graphics between Flutter and Android
version: 0.1.0
homepage: https://github.com/ueman/drawable
repository: https://github.com/ueman/drawable
issue_tracker: https://github.com/ueman/drawable/issues

environment:
  sdk: '>=3.2.4 <4.0.0'
  flutter: ">=3.16.8"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.11.1

flutter:
  plugin:
    platforms:
      android:
        package: de.ju.drawable
        pluginClass: DrawablePlugin